const router = require("express").Router();
const workerProfileController = require("../../controllers/workerProfile.controller");
const { workerVerifyJWT } = require("../../passport/common");
const {
  getReviewsCache,
  getCommentsCache,
  getBookingCache,
  getUpcomingBookingCache,
  getInProgressBookingCache,
  getCompletedBookingCache,
  getCancelledBookingCache,
  getWorkerReviewCache,
  getPopularWorkersCache,
  getNotificationsCache,
  getPaidBookingsCache,
  getPendingBookingCache,
} = require("../../cache/worker_cache");
const { mediaCache } = require("../../cache/media_cache");
const { getWorkerProfileCache } = require("../../cache/worker_profile");

router.get(
  "/:workerId",
  workerVerifyJWT,
  getWorkerProfileCache,
  workerProfileController.getWorkerProfile
);

router.get(
  "/:workerId/reviews",
  workerVerifyJWT,
  getReviewsCache,
  workerProfileController.getWorkerReview
);
router.get(
  "/:workerId/comments/:postId",
  workerVerifyJWT,
  getCommentsCache,
  workerProfileController.getWorkerComments
);
router.post(
  "/:workerId/comments",
  workerVerifyJWT,
  workerProfileController.addWorkerComments
);
router.patch(
  "/:workerId",
  workerVerifyJWT,
  workerProfileController.updateWorkerProfileDetails
);
router.post(
  "/:workerId/portfolio",
  workerVerifyJWT,
  workerProfileController.addWorkerPortfolio
);
router.get(
  "/:worker/portfolio/:page",
  workerVerifyJWT,
  mediaCache,
  workerProfileController.getWorkerPortfolio
);
router.post(
  "/:workerId/work-radius",
  workerVerifyJWT,
  workerProfileController.addWorkerRadius
);
router.get(
  "/:workerId/booking",
  workerVerifyJWT,
  getBookingCache,
  workerProfileController.getBooking
);
router.get(
  "/paid/:user",
  workerVerifyJWT,
  getPaidBookingsCache,
  workerProfileController.getPaidBooking
);
router.get(
  "/:workerId/booking-upcoming",
  workerVerifyJWT,
  getUpcomingBookingCache,
  workerProfileController.getUpcomingBooking
);
router.get(
  "/:workerId/booking-pending",
  workerVerifyJWT,
  workerProfileController.getPendingBooking
);
router.get(
  "/:workerId/booking-progress",
  workerVerifyJWT,
  workerProfileController.getBookingInProgress
);
router.get(
  "/:workerId/booking-completed",
  workerVerifyJWT,
  getCompletedBookingCache,
  workerProfileController.getCompletedBooking
);
router.get(
  "/:workerId/booking-cancelled",
  workerVerifyJWT,
  getCancelledBookingCache,
  workerProfileController.getCancelledBooking
);
router.put(
  "/booking-status",
  workerVerifyJWT,
  workerProfileController.updateBookingStatus
);
router.put(
  "/booking-status/pending",
  workerVerifyJWT,
  workerProfileController.markBookingAsPending
);
router.post(
  "/worker-review",
  workerVerifyJWT,
  workerProfileController.addWorkerReviews
);
router.get(
  "/:workerId/worker-review",
  workerVerifyJWT,
  getWorkerReviewCache,
  workerProfileController.getWorkerReviews
);
router.post(
  "/:workerId/available-slots",
  workerVerifyJWT,
  workerProfileController.addAvailableSlots
);
router.post(
  "/book-slot",
  workerVerifyJWT,
  workerProfileController.bookWorkerSlot
);
router.post(
  "/verify-payment",
  workerVerifyJWT,
  workerProfileController.verifyPaymentWebhook
);
router.post(
  "/refund/:ref",
  workerVerifyJWT,
  workerProfileController.refundWorker
);
router.post(
  "/cancel/:ref",
  workerVerifyJWT,
  workerProfileController.cancelWorker
);
router.patch(
  "/update-location",
  workerVerifyJWT,
  workerProfileController.updateLocation
);
router.patch(
  "/update-date",
  workerVerifyJWT,
  workerProfileController.updateDate
);
router.get(
  "/:worker/notify/",
  workerVerifyJWT,
  workerProfileController.notifyWorker
);
router.get(
  "/popular/:id",
  workerVerifyJWT,
  getPopularWorkersCache,
  workerProfileController.getPopular
);

module.exports.workerProfileRoute = router;
